# Generated by Django 6.0.4 on 2026-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restricao_Alimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restricao', models.CharField(max_length=100)),
                ('tipo_restricao', models.CharField(max_length=100)),
                ('descricao_restricao', models.CharField(max_length=200)),
                ('gravidade_restricao', models.CharField(max_length=100)),
            ],
        ),
    ]
